# Generated by Django 3.2.9 on 2022-11-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_userinfo_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product_sales', models.IntegerField()),
                ('product_photo', models.ImageField(upload_to='avatar/')),
            ],
        ),
    ]
