# Generated by Django 3.2.9 on 2022-11-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_photo',
            new_name='product_image',
        ),
    ]
