# Generated by Django 3.2.9 on 2022-11-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_product_photo_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_imageDetail',
            field=models.ImageField(default='', upload_to='avatar/'),
            preserve_default=False,
        ),
    ]
