# Generated by Django 3.2.9 on 2022-11-30 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.userinfo'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
