# Generated by Django 3.2.9 on 2022-11-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20221130_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_createtime',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
