# Generated by Django 3.2.9 on 2022-12-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_orderinfo_orderproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='business_address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='business_mobile',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='business_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='customer_address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='customer_mobile',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='customer_name',
            field=models.CharField(max_length=64),
        ),
    ]
