# Generated by Django 3.2.9 on 2022-12-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20221201_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
