# Generated by Django 3.2.14 on 2022-12-11 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_alter_orderinfo_order_createtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='business_area',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='business_city',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='business_province',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='customer_area',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='customer_city',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='customer_province',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='order_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_area',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_city',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_province',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_address',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_mobile',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_num', models.IntegerField()),
                ('stock_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stock_createtime', models.DateTimeField(auto_now_add=True)),
                ('business_province', models.CharField(max_length=16, null=True)),
                ('business_city', models.CharField(max_length=16, null=True)),
                ('business_area', models.CharField(max_length=16, null=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.userinfo')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.product')),
            ],
        ),
    ]
